/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yumxpress.gui;

import java.awt.Image;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import yumxpress.dao.CompanyDao;
import yumxpress.dao.OrderDao;
import yumxpress.dao.ProductDao;
import yumxpress.pojo.CartPojo;
import yumxpress.pojo.ProductPojo;
import yumxpress.util.UserProfile;

/**
 *
 * @author HP
 */
public class OrderFood extends javax.swing.JFrame {
    private Map<String,String>companyNameAndId;
    private List<ProductPojo>productsList;
    private int listIndex=0;
    private int size;
    private int watch=0;
    public OrderFood() {
        initComponents();
         super.setLocationRelativeTo(null);
         ImageIcon icon=new ImageIcon(getClass().getResource("/yumxpress/icons/Foodie.png"));
        Image image=icon.getImage();
        super.setIconImage(image);
        super.setResizable(false);
        loadCompaniesName();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblGreet = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnMyAccount = new javax.swing.JButton();
        btnMyCart = new javax.swing.JButton();
        btnCancelOrder = new javax.swing.JButton();
        btnOderHisory = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jcCompanies = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblFood2 = new javax.swing.JLabel();
        lblFood3 = new javax.swing.JLabel();
        lblFood4 = new javax.swing.JLabel();
        lblFood6 = new javax.swing.JLabel();
        lblFood5 = new javax.swing.JLabel();
        txtFoodPrice2 = new javax.swing.JTextField();
        txtFoodPrice3 = new javax.swing.JTextField();
        txtFoodPrice4 = new javax.swing.JTextField();
        txtFoodPrice5 = new javax.swing.JTextField();
        txtFoodPrice6 = new javax.swing.JTextField();
        lblLeft = new javax.swing.JLabel();
        txtFoodPrice1 = new javax.swing.JTextField();
        lblFood1 = new javax.swing.JLabel();
        lblRight = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGreet.setBackground(new java.awt.Color(255, 51, 255));
        lblGreet.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblGreet.setForeground(new java.awt.Color(255, 255, 255));
        lblGreet.setText("       Hello Punit");
        jPanel2.add(lblGreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 181, 33));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 217, 267, 17));

        btnMyAccount.setBackground(new java.awt.Color(255, 153, 51));
        btnMyAccount.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnMyAccount.setText("My Account");
        btnMyAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyAccountActionPerformed(evt);
            }
        });
        jPanel2.add(btnMyAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 221, -1));

        btnMyCart.setBackground(new java.awt.Color(255, 153, 51));
        btnMyCart.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnMyCart.setText("My Cart");
        btnMyCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyCartActionPerformed(evt);
            }
        });
        jPanel2.add(btnMyCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 221, -1));

        btnCancelOrder.setBackground(new java.awt.Color(255, 153, 51));
        btnCancelOrder.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnCancelOrder.setText("Cancel Order");
        btnCancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelOrderActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 221, -1));

        btnOderHisory.setBackground(new java.awt.Color(255, 153, 51));
        btnOderHisory.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnOderHisory.setText("Order History");
        btnOderHisory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOderHisoryActionPerformed(evt);
            }
        });
        jPanel2.add(btnOderHisory, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 221, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumxpress/icons/user.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 160, 150));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, -7, 280, 630));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 255));
        jLabel1.setText("Order Food");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, 58));

        jcCompanies.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jcCompanies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCompaniesActionPerformed(evt);
            }
        });
        jPanel1.add(jcCompanies, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, 200, 27));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 0));
        jLabel2.setText("FILTER");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, -1, -1));

        lblFood2.setBackground(new java.awt.Color(255, 255, 255));
        lblFood2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 30)); // NOI18N
        lblFood2.setForeground(new java.awt.Color(51, 0, 51));
        lblFood2.setOpaque(true);
        lblFood2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMuseClicked(evt);
            }
        });
        jPanel1.add(lblFood2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 209, 160));

        lblFood3.setBackground(new java.awt.Color(255, 255, 255));
        lblFood3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 30)); // NOI18N
        lblFood3.setForeground(new java.awt.Color(51, 0, 51));
        lblFood3.setOpaque(true);
        lblFood3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMuseClicked(evt);
            }
        });
        jPanel1.add(lblFood3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 140, 209, 160));

        lblFood4.setBackground(new java.awt.Color(255, 255, 255));
        lblFood4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 30)); // NOI18N
        lblFood4.setForeground(new java.awt.Color(51, 0, 51));
        lblFood4.setOpaque(true);
        lblFood4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMuseClicked(evt);
            }
        });
        jPanel1.add(lblFood4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 209, 160));

        lblFood6.setBackground(new java.awt.Color(255, 255, 255));
        lblFood6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 30)); // NOI18N
        lblFood6.setForeground(new java.awt.Color(51, 0, 51));
        lblFood6.setOpaque(true);
        lblFood6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMuseClicked(evt);
            }
        });
        jPanel1.add(lblFood6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 370, 209, 160));

        lblFood5.setBackground(new java.awt.Color(255, 255, 255));
        lblFood5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 30)); // NOI18N
        lblFood5.setForeground(new java.awt.Color(51, 0, 51));
        lblFood5.setOpaque(true);
        lblFood5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMuseClicked(evt);
            }
        });
        jPanel1.add(lblFood5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 209, 160));

        txtFoodPrice2.setEditable(false);
        txtFoodPrice2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtFoodPrice2.setForeground(new java.awt.Color(51, 0, 51));
        txtFoodPrice2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMuseClicked(evt);
            }
        });
        jPanel1.add(txtFoodPrice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 110, 30));

        txtFoodPrice3.setEditable(false);
        txtFoodPrice3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtFoodPrice3.setForeground(new java.awt.Color(51, 0, 51));
        txtFoodPrice3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMuseClicked(evt);
            }
        });
        jPanel1.add(txtFoodPrice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 320, 112, 30));

        txtFoodPrice4.setEditable(false);
        txtFoodPrice4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtFoodPrice4.setForeground(new java.awt.Color(51, 0, 51));
        txtFoodPrice4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMuseClicked(evt);
            }
        });
        jPanel1.add(txtFoodPrice4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, 110, 30));

        txtFoodPrice5.setEditable(false);
        txtFoodPrice5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtFoodPrice5.setForeground(new java.awt.Color(51, 0, 51));
        txtFoodPrice5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMuseClicked(evt);
            }
        });
        jPanel1.add(txtFoodPrice5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 550, 110, -1));

        txtFoodPrice6.setEditable(false);
        txtFoodPrice6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtFoodPrice6.setForeground(new java.awt.Color(51, 0, 51));
        txtFoodPrice6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMuseClicked(evt);
            }
        });
        jPanel1.add(txtFoodPrice6, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 550, 120, -1));

        lblLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumxpress/icons/icons8-left-arrow-64 (1).png"))); // NOI18N
        lblLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLeftMouseClicked(evt);
            }
        });
        jPanel1.add(lblLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 70, 84));

        txtFoodPrice1.setEditable(false);
        txtFoodPrice1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtFoodPrice1.setForeground(new java.awt.Color(51, 0, 51));
        txtFoodPrice1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMuseClicked(evt);
            }
        });
        jPanel1.add(txtFoodPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 100, 30));

        lblFood1.setBackground(new java.awt.Color(255, 255, 255));
        lblFood1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 30)); // NOI18N
        lblFood1.setForeground(new java.awt.Color(51, 0, 51));
        lblFood1.setOpaque(true);
        lblFood1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMouseClicked(evt);
            }
        });
        jPanel1.add(lblFood1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 209, 160));

        lblRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumxpress/icons/icons8-right-arrow-64 (1).png"))); // NOI18N
        lblRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRightMouseClicked(evt);
            }
        });
        jPanel1.add(lblRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 310, 70, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 1200, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumxpress/icons/user.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 160, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMyAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyAccountActionPerformed
        MyAccount account=new MyAccount();
        account.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMyAccountActionPerformed

    private void btnMyCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyCartActionPerformed
        MyCart options = new MyCart();
            options.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnMyCartActionPerformed

    private void btnCancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelOrderActionPerformed
        CancelOrder  order=new CancelOrder();
        order.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelOrderActionPerformed

    private void btnOderHisoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOderHisoryActionPerformed
      OrderHistory history=new OrderHistory();
      history.setVisible(true);
      this.dispose();
      
    }//GEN-LAST:event_btnOderHisoryActionPerformed

    private void jcCompaniesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCompaniesActionPerformed
        emptyAll();   
        listIndex=0;
        try{
           String id;
//           if(jcCompanies.getSelectedIndex()==0){
//              id="ALL";
//           }
//           else{
               id=companyNameAndId.get(jcCompanies.getSelectedItem().toString());
//           }
            productsList=ProductDao.getProductsDetail(id);
            
            

            size=productsList.size();
            addImages();
            
       }
       catch(SQLException ex){
            
            JOptionPane.showMessageDialog(null,"DB problem "+ex);
            ex.printStackTrace();
        }
        catch(IOException ex){
            JOptionPane.showMessageDialog(null,"IO exception "+ex);
            ex.printStackTrace();   
        }
    }//GEN-LAST:event_jcCompaniesActionPerformed

    private void lblMuseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMuseClicked
        JLabel lbl=(JLabel)evt.getSource();
        int index=Integer.parseInt(lbl.getName());
        if(index>=productsList.size()){
            JOptionPane.showMessageDialog(null,"You Selected Not Available FoodItem ");
            return;
        }
        String arr[]={"Add to cart","Buy Now"};
        int ans=JOptionPane.showOptionDialog(null,"What do you want to do","confirm",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null, arr, NORMAL);
        if(ans==1){
            PlaceOrder frame=new PlaceOrder(productsList.get(index));
            frame.setVisible(true);
            this.dispose();
        }
        if(ans==0){
            ProductPojo pojo=productsList.get(index);
            CartPojo cartPojo=new CartPojo();
            cartPojo.setProductId(pojo.getProductId());
            
            cartPojo.setCustomerId(UserProfile.getId());
            System.err.println(cartPojo.getCustomerId());
            cartPojo.setCompanyId(pojo.getCompanyId());
            try{
                String result=OrderDao.addToCart(cartPojo);
                
                    JOptionPane.showMessageDialog(null,result);
                
               
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(null,"Alraedy Added to the cart!!");
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Alraedy Added to the cart!!");
            }
        }
    }//GEN-LAST:event_lblMuseClicked

    private void lblLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLeftMouseClicked
      int t=listIndex;
      if(t%6==0){
         t=t-12;
      }
      else if(t%6==1){
          t=t-7;
      }
      else if(t%6==2){
          t=t-8;
      }
      else if(t%6==3){
          t=t-9;
      }
      else if(t%6==4){
          t=t-10;
      }
      else if(t%6==5){
          t=t-11;
      }
      if(t<0){
          JOptionPane.showMessageDialog(null,"No more food item available");
          return;
      }
      listIndex=t;
      addImages();
    }//GEN-LAST:event_lblLeftMouseClicked

    private void lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMouseClicked
        JLabel lbl=(JLabel)evt.getSource();
        int index=Integer.parseInt(lbl.getName());
        if(index>=productsList.size()){
            JOptionPane.showMessageDialog(null,"You Selected Not Available FoodItem ");
            return;
        }
        String arr[]={"Add to cart","Buy Now"};
        int ans=JOptionPane.showOptionDialog(null,"What do you want to do","confirm",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null, arr, NORMAL);
        if(ans==1){
            PlaceOrder frame=new PlaceOrder(productsList.get(index));
            frame.setVisible(true);
            this.dispose();
        }
        System.out.println(ans);
        if(ans==0){
            ProductPojo pojo=productsList.get(index);
            CartPojo cartPojo=new CartPojo();
            cartPojo.setProductId(pojo.getProductId());
            cartPojo.setCustomerId(UserProfile.getId());
            cartPojo.setCompanyId(pojo.getCompanyId());
            try{
               String result=OrderDao.addToCart(cartPojo);
               JOptionPane.showMessageDialog(null,result);
                
                
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(null,ex);
            }
            
        }
    }//GEN-LAST:event_lblMouseClicked

    private void lblRightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRightMouseClicked
      int t=listIndex;
      if(t%6==0){
        t=t+0;
      }
      else if(t%6==1){
          t=t+1;
      }
      else if(t%6==2){
          t=t+2;
      }
      else if(t%6==3){
          t=t+3;
      }
      else if(t%6==4){
          t=t+4;
      }
      else if(t%6==5){
          t=t+5;
      }
      if(t>=productsList.size()){
          JOptionPane.showMessageDialog(null,"No more food item available");
          return;
      }
      listIndex=t;
      addImages();
             
    }//GEN-LAST:event_lblRightMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderFood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelOrder;
    private javax.swing.JButton btnMyAccount;
    private javax.swing.JButton btnMyCart;
    private javax.swing.JButton btnOderHisory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> jcCompanies;
    private javax.swing.JLabel lblFood1;
    private javax.swing.JLabel lblFood2;
    private javax.swing.JLabel lblFood3;
    private javax.swing.JLabel lblFood4;
    private javax.swing.JLabel lblFood5;
    private javax.swing.JLabel lblFood6;
    private javax.swing.JLabel lblGreet;
    private javax.swing.JLabel lblLeft;
    private javax.swing.JLabel lblRight;
    private javax.swing.JTextField txtFoodPrice1;
    private javax.swing.JTextField txtFoodPrice2;
    private javax.swing.JTextField txtFoodPrice3;
    private javax.swing.JTextField txtFoodPrice4;
    private javax.swing.JTextField txtFoodPrice5;
    private javax.swing.JTextField txtFoodPrice6;
    // End of variables declaration//GEN-END:variables

    private void loadCompaniesName() {
        try{
            companyNameAndId=CompanyDao.getCompanyNameAndId();
            if(companyNameAndId.isEmpty()){
                JOptionPane.showMessageDialog(null,"0 Comapies are available");
                return;
            }
            Set<String>companyName=companyNameAndId.keySet();
//            jcCompanies.addItem("ALL");
            for(String name:companyName){
                jcCompanies.addItem(name);
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"DB error in loading companies company names"+ex);
        }
    }

    private void addImages() {
        if(size>listIndex){
            ProductPojo product=productsList.get(listIndex);
            
            Image image=product.getProductimage();
           
            image=image.getScaledInstance(lblFood1.getWidth(),lblFood1.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon icon=new ImageIcon(image);
            lblFood1.setIcon(icon);
            txtFoodPrice1.setText(product.getProductPrice()+"");
            txtFoodPrice1.setName(listIndex+"");
            lblFood1.setName(listIndex+"");
            listIndex++;
        }
        else{
            lblFood1.setIcon(null);
            lblFood1.setText("N/A");
            txtFoodPrice1.setText("N/A");
            txtFoodPrice1.setName(listIndex+"");
            lblFood1.setName(listIndex+"");
            listIndex++;
        }
        if(size>listIndex){
           
            ProductPojo product=productsList.get(listIndex);
            Image image=product.getProductimage();
           
            image=image.getScaledInstance(lblFood2.getWidth(),lblFood2.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon icon=new ImageIcon(image);
            lblFood2.setIcon(icon);
            txtFoodPrice2.setText(product.getProductPrice()+"");
            txtFoodPrice2.setName(listIndex+"");
            lblFood2.setName(listIndex+"");
            listIndex++;
        }
        else{
            lblFood2.setIcon(null);
            lblFood2.setText("N/A");
            txtFoodPrice2.setText("N/A");
            txtFoodPrice2.setName(listIndex+"");
            lblFood2.setName(listIndex+"");
            listIndex++;
        }
        if(size>listIndex){
           
            ProductPojo product=productsList.get(listIndex);
            Image image=product.getProductimage();
            image=image.getScaledInstance(lblFood3.getWidth(),lblFood3.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon icon=new ImageIcon(image);
            
            lblFood3.setIcon(icon);
            txtFoodPrice3.setText(product.getProductPrice()+"");
            txtFoodPrice3.setName(listIndex+"");
            lblFood3.setName(listIndex+"");
            listIndex++;
        }
        else{
            
            lblFood3.setIcon(null);
            lblFood3.setText("N/A");
            txtFoodPrice3.setText("N/A");
            txtFoodPrice3.setName(listIndex+"");
            lblFood3.setName(listIndex+"");
            listIndex++;
        }
        if(size>listIndex){
            
            ProductPojo product=productsList.get(listIndex);
            Image image=product.getProductimage();
            image=image.getScaledInstance(lblFood4.getWidth(),lblFood4.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon icon=new ImageIcon(image);
            lblFood4.setIcon(icon);
            
           
            txtFoodPrice4.setText(product.getProductPrice()+"");
            txtFoodPrice4.setName(listIndex+"");
            lblFood4.setName(listIndex+"");
            listIndex++;
        }
        else{
            lblFood4.setIcon(null);
            lblFood4.setText("N/A");
            txtFoodPrice4.setText("N/A");
            txtFoodPrice4.setName(listIndex+"");
            lblFood4.setName(listIndex+"");
            listIndex++;
        }
        if(size>listIndex){
            ProductPojo product=productsList.get(listIndex);
            Image image=product.getProductimage();
            image=image.getScaledInstance(lblFood5.getWidth(),lblFood5.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon icon=new ImageIcon(image);
            lblFood5.setIcon(icon);
            txtFoodPrice5.setText(product.getProductPrice()+"");
            txtFoodPrice5.setName(listIndex+"");
            lblFood5.setName(listIndex+"");
            listIndex++;
        }
        else{
            lblFood5.setIcon(null);
            lblFood5.setText("N/A");
            txtFoodPrice5.setText("N/A");
            txtFoodPrice5.setName(listIndex+"");
            lblFood5.setName(listIndex+"");
            listIndex++;
        }
        if(size>listIndex){
            
            ProductPojo product=productsList.get(listIndex);
            Image image=product.getProductimage();
            image=image.getScaledInstance(lblFood6.getWidth(),lblFood6.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon icon=new ImageIcon(image);
            lblFood6.setIcon(icon);
            txtFoodPrice6.setText(product.getProductPrice()+"");
            txtFoodPrice6.setName(listIndex+"");
            lblFood6.setName(listIndex+"");
            listIndex++;
        }
        else{
            lblFood6.setIcon(null);
            lblFood6.setText("   N/A");
            txtFoodPrice6.setText("N/A");
            txtFoodPrice6.setName(listIndex+"");
            lblFood6.setName(listIndex+"");
            listIndex++;
        }
        
    }

    private void emptyAll() {
       this.lblFood2.setIcon(null);
       this.lblFood2.setIcon(null);
       this.lblFood3.setIcon(null);
       this.lblFood4.setIcon(null);
       this.lblFood5.setIcon(null);
       this.lblFood6.setIcon(null);
       
       this.txtFoodPrice1.setText("");
       this.txtFoodPrice2.setText("");
       this.txtFoodPrice3.setText("");
       this.txtFoodPrice4.setText("");
       this.txtFoodPrice5.setText("");
       this.txtFoodPrice6.setText("");
       
    }

  
}
