/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yumxpress.gui;

import java.awt.Image;
import java.sql.SQLException;
import java.util.Map;
import javax.mail.MessagingException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import yumxpress.dao.CompanyDao;
import yumxpress.dao.OrderDao;
import yumxpress.dao.StaffDao;
import yumxpress.pojo.OrderPojo;
import yumxpress.pojo.PlaceOrderPojo;
import yumxpress.pojo.ProductPojo;
import yumxpress.util.UserProfile;
import yumxpress.util.Mailer;
import yumxpress.util.OwnerProfile;

/**
 *
 * @author HP
 */
public class PlaceOrder extends javax.swing.JFrame {
    private ProductPojo pojo;
    public PlaceOrder() {
        initComponents();
        super.setLocationRelativeTo(null);
        ImageIcon icon=new ImageIcon(getClass().getResource("/yumxpress/icons/Foodie.png"));
        Image image=icon.getImage();
        super.setIconImage(image);
        super.setResizable(false);
        lblGreet.setText("Hello "+UserProfile.getName());
    }

    public PlaceOrder(ProductPojo pojo) {
        this();
        this.pojo=pojo;
        Image image = pojo.getProductimage();
         System.out.println(image);
        image = image.getScaledInstance(lblFoodImage.getWidth(), lblFoodImage.getHeight(), Image.SCALE_SMOOTH);
       
        ImageIcon icon = new ImageIcon(image);
        lblFoodImage.setIcon(icon);
        txtPrice.setText(pojo.getProductPrice()+"");
        txtFoodName.setText(pojo.getProductName());
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnMyCart1 = new javax.swing.JButton();
        btnOrderFood1 = new javax.swing.JButton();
        btnCancelOrder1 = new javax.swing.JButton();
        btnOrderHistory1 = new javax.swing.JButton();
        btnLogOut1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        lblGreet = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFoodName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        lblFoodImage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnOrder = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(51, 51, 255));

        jPanel6.setBackground(new java.awt.Color(51, 51, 255));

        btnMyCart1.setBackground(new java.awt.Color(255, 153, 0));
        btnMyCart1.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        btnMyCart1.setForeground(new java.awt.Color(51, 51, 0));
        btnMyCart1.setText("My Cart");
        btnMyCart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyCart1ActionPerformed(evt);
            }
        });

        btnOrderFood1.setBackground(new java.awt.Color(255, 153, 0));
        btnOrderFood1.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        btnOrderFood1.setForeground(new java.awt.Color(51, 51, 0));
        btnOrderFood1.setText("Order Food");
        btnOrderFood1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderFood1ActionPerformed(evt);
            }
        });

        btnCancelOrder1.setBackground(new java.awt.Color(255, 153, 0));
        btnCancelOrder1.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        btnCancelOrder1.setForeground(new java.awt.Color(51, 51, 0));
        btnCancelOrder1.setText("Cancel Order");
        btnCancelOrder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelOrder1ActionPerformed(evt);
            }
        });

        btnOrderHistory1.setBackground(new java.awt.Color(255, 153, 0));
        btnOrderHistory1.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        btnOrderHistory1.setForeground(new java.awt.Color(51, 51, 0));
        btnOrderHistory1.setText("Order History");
        btnOrderHistory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderHistory1ActionPerformed(evt);
            }
        });

        btnLogOut1.setBackground(new java.awt.Color(255, 153, 0));
        btnLogOut1.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        btnLogOut1.setForeground(new java.awt.Color(51, 51, 0));
        btnLogOut1.setText("LogOut");
        btnLogOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOut1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMyCart1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrderFood1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrderHistory1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(btnLogOut1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnMyCart1)
                .addGap(32, 32, 32)
                .addComponent(btnOrderFood1)
                .addGap(27, 27, 27)
                .addComponent(btnCancelOrder1)
                .addGap(32, 32, 32)
                .addComponent(btnOrderHistory1)
                .addGap(33, 33, 33)
                .addComponent(btnLogOut1)
                .addContainerGap())
        );

        lblGreet.setBackground(new java.awt.Color(204, 51, 255));
        lblGreet.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblGreet.setForeground(new java.awt.Color(255, 255, 255));
        lblGreet.setText("       Hello Punit");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumxpress/icons/user.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGreet, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGreet, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtFoodName.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        txtFoodName.setForeground(new java.awt.Color(0, 153, 255));
        jPanel1.add(txtFoodName, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 179, 29));

        txtPrice.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(0, 153, 255));
        jPanel1.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 180, 27));
        jPanel1.add(lblFoodImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 206, 400, 188));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("Food Name :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("Food Price :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, -1, -1));

        btnOrder.setBackground(new java.awt.Color(102, 153, 255));
        btnOrder.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        btnOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnOrder.setText("Order");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        jPanel1.add(btnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 200, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 49)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("Place Order");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 260, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMyCart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyCart1ActionPerformed
        MyCart myCart = new MyCart();
        myCart.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMyCart1ActionPerformed

    private void btnOrderFood1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderFood1ActionPerformed
        OrderFood orderFood = new OrderFood();
        orderFood.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOrderFood1ActionPerformed

    private void btnCancelOrder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelOrder1ActionPerformed
        CancelOrder cancelOrder = new CancelOrder();
        cancelOrder.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelOrder1ActionPerformed

    private void btnOrderHistory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderHistory1ActionPerformed
        OrderHistory orderHistory = new OrderHistory();
        orderHistory.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOrderHistory1ActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
      try{
         
            String staffid=StaffDao.randomStaffIdByCompanyId(pojo.getCompanyId());
            PlaceOrderPojo placeOrderPojo=new PlaceOrderPojo();
            placeOrderPojo.setCompanyId(pojo.getCompanyId());
            placeOrderPojo.setStaffId(staffid);
            placeOrderPojo.setCustomerId(UserProfile.getId());
            placeOrderPojo.setProductId(pojo.getProductId());
            if(OrderDao.placeOrder(placeOrderPojo)){
                JOptionPane.showMessageDialog(null,"Order Placed");
            }
            else{
                JOptionPane.showMessageDialog(null,"Order can not be placed");
                return;
            }
            OrderPojo orderPojo=OrderDao.getOrderDetailByOrderId(placeOrderPojo.getOrderId());
            orderPojo.setCustomerName(UserProfile.getName());
            orderPojo.setOrderId(placeOrderPojo.getOrderId());
            Map<String,String>emailCredintials=CompanyDao.getEmailCredintialByCompanyId(pojo.getCompanyId());
            Mailer.sendMail(emailCredintials, orderPojo);
            JOptionPane.showMessageDialog(null,"Mail Sent");
            
        }
        catch(SQLException ex){
         JOptionPane.showMessageDialog(null,"Exceptio in placeorder"+ex);
         ex.printStackTrace();
        }
      catch(MessagingException ex){
          JOptionPane.showMessageDialog(null,"Prolem in sending the mail"+ex);
      }
      catch(Exception ex){
          JOptionPane.showMessageDialog(null,"Prolem in sending the mail"+ex);
          ex.printStackTrace();
      }
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnLogOut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOut1ActionPerformed
       CustomerLogin login=new CustomerLogin();
       login.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnLogOut1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelOrder1;
    private javax.swing.JButton btnLogOut1;
    private javax.swing.JButton btnMyCart1;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnOrderFood1;
    private javax.swing.JButton btnOrderHistory1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblFoodImage;
    private javax.swing.JLabel lblGreet;
    private javax.swing.JTextField txtFoodName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
